import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import NovoAgendamentoForm from './components/NovoAgendamentoForm';
import DashboardNovo from './components/DashboardNovo';
import CronogramaPage from './components/CronogramaPage';
import LoginPage from './components/LoginPage';
import { useAuth } from './contexts/AuthContext';
import './App.css';
function App() {
    const { user, logout, isAdmin } = useAuth();
    const [activeTab, setActiveTab] = useState('novo');
    // Se não estiver autenticado, mostrar página de login
    if (!user) {
        return _jsx(LoginPage, {});
    }
    return (_jsxs("div", { className: "min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50", children: [_jsx("header", { className: "bg-white/80 backdrop-blur-md sticky top-0 z-50 shadow-lg border-b border-white/20", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "flex items-center justify-between py-4", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("img", { src: "https://logodownload.org/wp-content/uploads/2018/07/universidade-anhanguera-logo-1.png", alt: "Universidade Anhanguera", className: "h-16 w-auto object-contain" }), _jsx("div", { className: "border-l-2 border-gray-300 h-12 mx-2" }), _jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent", children: "Sistema de Agendamento" }), _jsx("p", { className: "text-sm text-gray-500", children: "Gest\u00E3o de Laborat\u00F3rios de Inform\u00E1tica" })] })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("div", { className: "text-right", children: [_jsx("p", { className: "text-sm font-bold text-gray-900", children: user.fullName }), _jsx("p", { className: "text-xs text-gray-500", children: user.role === 'admin' ? '👑 Administrador' : '👨‍🏫 Professor' })] }), _jsxs("button", { onClick: logout, className: "px-4 py-2 bg-red-500 hover:bg-red-600 text-white rounded-xl font-semibold transition-all hover:scale-105 active:scale-95 flex items-center space-x-2", children: [_jsx("svg", { className: "w-4 h-4", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" }) }), _jsx("span", { children: "Sair" })] })] })] }), _jsxs("nav", { className: "flex space-x-2 pb-4 overflow-x-auto scrollbar-hide", children: [_jsxs("button", { onClick: () => setActiveTab('novo'), className: `group relative px-6 py-3 rounded-xl font-semibold transition-all duration-300 whitespace-nowrap ${activeTab === 'novo'
                                        ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-lg shadow-indigo-500/50 scale-105'
                                        : 'bg-white text-gray-700 hover:bg-gray-50 hover:scale-105 shadow-md'}`, children: [_jsxs("span", { className: "flex items-center space-x-2", children: [_jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M12 4v16m8-8H4" }) }), _jsx("span", { children: "Novo Agendamento" })] }), activeTab === 'novo' && (_jsx("div", { className: "absolute bottom-0 left-0 right-0 h-1 bg-white rounded-full" }))] }), _jsxs("button", { onClick: () => setActiveTab('dashboard'), className: `group relative px-6 py-3 rounded-xl font-semibold transition-all duration-300 whitespace-nowrap ${activeTab === 'dashboard'
                                        ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-lg shadow-indigo-500/50 scale-105'
                                        : 'bg-white text-gray-700 hover:bg-gray-50 hover:scale-105 shadow-md'}`, children: [_jsxs("span", { className: "flex items-center space-x-2", children: [_jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" }) }), _jsx("span", { children: "Dashboard" })] }), activeTab === 'dashboard' && (_jsx("div", { className: "absolute bottom-0 left-0 right-0 h-1 bg-white rounded-full" }))] }), isAdmin && (_jsxs("button", { onClick: () => setActiveTab('cronograma'), className: `group relative px-6 py-3 rounded-xl font-semibold transition-all duration-300 whitespace-nowrap ${activeTab === 'cronograma'
                                        ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-lg shadow-indigo-500/50 scale-105'
                                        : 'bg-white text-gray-700 hover:bg-gray-50 hover:scale-105 shadow-md'}`, children: [_jsxs("span", { className: "flex items-center space-x-2", children: [_jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" }) }), _jsx("span", { children: "Gerenciar Cronograma" })] }), activeTab === 'cronograma' && (_jsx("div", { className: "absolute bottom-0 left-0 right-0 h-1 bg-white rounded-full" }))] }))] })] }) }), _jsxs("main", { className: "transition-all duration-500", children: [activeTab === 'novo' && _jsx(NovoAgendamentoForm, {}), activeTab === 'dashboard' && _jsx(DashboardNovo, {}), activeTab === 'cronograma' && isAdmin && _jsx(CronogramaPage, {})] })] }));
}
export default App;
